"use client";
import {useState} from "react";
import {IconBriefcase,IconFileInvoice,IconFolder,IconHeartbeat,IconUsers} from "@tabler/icons-react";
import styles from "./rh.module.css";

const tabs=[{id:"people",label:"Colaboradores",icon:IconUsers},{id:"payroll",label:"Folha e guias",icon:IconFileInvoice},{id:"health",label:"ASO e saúde",icon:IconHeartbeat},{id:"jobs",label:"Recrutamento",icon:IconBriefcase},{id:"vault",label:"Cofre e currículos",icon:IconFolder}];
export function RHExperience(){const[active,setActive]=useState("people");return <div className={styles.experience}><div className={styles.tabs} role="tablist">{tabs.map(tab=>{const Icon=tab.icon;return <button type="button" key={tab.id} role="tab" aria-selected={active===tab.id} className={active===tab.id?styles.active:""} onClick={()=>setActive(tab.id)}><Icon/><span>{tab.label}</span></button>})}</div><div className={styles.screen}><div className={styles.appbar}><b><span>LOGGXY</span> RH</b><small>Gestão de pessoas</small><i>RH</i></div>
{active==="people"&&<Panel title="Controle de funcionários" label="COLABORADORES ATIVOS"><div className={styles.metrics}>{[["Colaboradores","128"],["Departamentos","12"],["Admissões no mês","8"],["Pendências","5"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></article>)}</div><Table rows={[["Mariana Silva","Financeiro","Ativo"],["Rafael Costa","Operações","Ativo"],["Carla Souza","Comercial","Férias"],["João Lima","Tecnologia","Ativo"]]}/></Panel>}
{active==="payroll"&&<Panel title="Tratamento da folha" label="FOLHA, GUIAS E eSOCIAL"><div className={styles.steps}>{["Importar eventos","Conferir cálculos","Validar pendências","Emitir guias","Preparar eSocial"].map((x,i)=><article key={x}><b>{i+1}</b><span>{x}</span><em>{i<3?"Concluído":"Pendente"}</em></article>)}</div></Panel>}
{active==="health"&&<Panel title="Saúde ocupacional" label="ASO E VENCIMENTOS"><div className={styles.cards}>{[["ASOs válidos","116","90%"],["Vencem em 30 dias","9","55%"],["Pendentes","3","24%"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><div><i style={{width:x[2]}}/></div></article>)}</div><Table rows={[["Mariana Silva","Periódico","18/08/2026"],["Rafael Costa","Admissional","22/08/2026"],["Carla Souza","Retorno","02/09/2026"]]}/></Panel>}
{active==="jobs"&&<Panel title="Balcão de vagas" label="RECRUTAMENTO E SELEÇÃO"><div className={styles.jobs}>{[["Analista Financeiro","24 currículos","Em triagem"],["Assistente de Logística","38 currículos","Entrevistas"],["Consultor Comercial","19 currículos","Publicado"]].map(x=><article key={x[0]}><IconBriefcase/><span><b>{x[0]}</b><small>{x[1]}</small></span><em>{x[2]}</em></article>)}</div></Panel>}
{active==="vault"&&<Panel title="Cofre de colaboradores" label="ARQUIVOS E CURRÍCULOS"><div className={styles.vaultGrid}>{[["Documentos pessoais","842 arquivos"],["Contratos e termos","386 arquivos"],["ASOs e atestados","274 arquivos"],["Currículos","619 arquivos"]].map(x=><article key={x[0]}><IconFolder/><span><b>{x[0]}</b><small>{x[1]}</small></span></article>)}</div></Panel>}</div></div>}
function Panel({title,label,children}:{title:string,label:string,children:React.ReactNode}){return <div className={styles.panel}><header><div><span>{label}</span><h3>{title}</h3></div><button>+ Novo registro</button></header>{children}</div>}
function Table({rows}:{rows:string[][]}){return <div className={styles.table}><header><span>Colaborador</span><span>Área / Tipo</span><span>Status / Data</span></header>{rows.map(row=><article key={row[0]}>{row.map(cell=><span key={cell}>{cell}</span>)}</article>)}</div>}
