"use client";

import {useState} from "react";
import {IconCash,IconCheck,IconFileInvoice,IconMapPin,IconPackage,IconTruck,IconUpload} from "@tabler/icons-react";
import styles from "./logistica.module.css";

const tabs=[
  {id:"tracking",label:"Rastreamento",icon:IconMapPin},
  {id:"cte",label:"CT-e e cofre",icon:IconFileInvoice},
  {id:"fleet",label:"Frota",icon:IconTruck},
  {id:"pickup",label:"Coletas",icon:IconPackage},
  {id:"finance",label:"Financeiro",icon:IconCash},
];

export function LogisticsExperience(){
  const [active,setActive]=useState("tracking");
  return <div className={styles.experience}>
    <div className={styles.tabs} role="tablist" aria-label="Recursos da Loggxy Logística">{tabs.map(tab=>{const Icon=tab.icon;return <button type="button" key={tab.id} role="tab" aria-selected={active===tab.id} className={active===tab.id?styles.tabActive:""} onClick={()=>setActive(tab.id)}><Icon/><span>{tab.label}</span></button>})}</div>
    <div className={styles.screen} role="tabpanel">
      <div className={styles.appbar}><div><span>LOGGXY</span> LOGÍSTICA</div><small>Torre de controle</small><i>OP</i></div>
      {active==="tracking"&&<div className={styles.tracking}><div className={styles.screenHead}><div><span>RASTREAMENTO EM TEMPO REAL</span><h3>Cargas em movimento</h3></div><button>Atualizado agora</button></div><div className={styles.trackingGrid}><div className={styles.map}><div className={styles.mapGrid}/><div className={styles.roadA}/><div className={styles.roadB}/><span className={`${styles.pin} ${styles.pinA}`}><IconTruck/></span><span className={`${styles.pin} ${styles.pinB}`}><IconTruck/></span><span className={`${styles.pin} ${styles.pinC}`}><IconMapPin/></span><div className={styles.routeInfo}><b>SP → Campinas</b><small>Previsão 16:40 · 62 km restantes</small></div></div><aside>{[["LGX-2048","Em trânsito","São Paulo → Campinas"],["LGX-1987","Em coleta","Guarulhos → Santos"],["LGX-1932","Entregue","Jundiaí → Sorocaba"]].map(([code,status,route])=><article key={code}><i className={status==="Entregue"?styles.done:""}/><span><b>{code}</b><small>{route}</small></span><em>{status}</em></article>)}</aside></div></div>}
      {active==="cte"&&<div className={styles.documents}><div className={styles.screenHead}><div><span>GESTOR DE CT-e E COFRE DIGITAL</span><h3>Documentos da operação</h3></div><button><IconUpload/> Enviar arquivo</button></div><div className={styles.docStats}><article><IconFileInvoice/><span><b>1.248</b>CT-es arquivados</span></article><article><IconCheck/><span><b>982</b>Comprovantes vinculados</span></article><article><IconPackage/><span><b>18,4 GB</b>Documentos protegidos</span></article></div><div className={styles.docTable}><header><span>Documento</span><span>Cliente</span><span>Emissão</span><span>Status</span></header>{[["CT-e 000.012.448","Indústria Alfa","14/07/2026","Completo"],["CT-e 000.012.447","Comercial Beta","14/07/2026","Aguardando comprovante"],["CT-e 000.012.446","Distribuidora Gama","13/07/2026","Completo"],["Romaneio 00481","Operação Sul","13/07/2026","Arquivado"]].map(row=><article key={row[0]}>{row.map((cell,index)=><span className={index===3?(cell==="Completo"||cell==="Arquivado"?styles.statusOk:styles.statusWait):""} key={cell}>{cell}</span>)}</article>)}</div></div>}
      {active==="fleet"&&<div className={styles.fleet}><div className={styles.screenHead}><div><span>GESTÃO DE VEÍCULOS</span><h3>Frota sob controle</h3></div><button>+ Cadastrar veículo</button></div><div className={styles.fleetMetrics}><article><span>Veículos ativos</span><b>42</b><small>38 em operação</small></article><article><span>Disponíveis</span><b>8</b><small>Prontos para viagem</small></article><article><span>Manutenção</span><b>4</b><small>2 preventivas</small></article><article><span>Ocupação média</span><b>84%</b><small>+6% este mês</small></article></div><div className={styles.vehicleList}>{[["ABC-4D21","Volvo FH 540","Em viagem","Campinas / SP"],["DEF-8G72","Mercedes Actros","Disponível","Matriz"],["GHI-2J19","DAF XF 480","Manutenção","Oficina parceira"],["JKL-7M44","Iveco Daily","Em coleta","Guarulhos / SP"]].map(item=><article key={item[0]}><IconTruck/><span><b>{item[0]}</b><small>{item[1]}</small></span><em>{item[2]}</em><i>{item[3]}</i></article>)}</div></div>}
      {active==="pickup"&&<div className={styles.pickups}><div className={styles.screenHead}><div><span>ORDEM E CONTROLE DE COLETAS</span><h3>Programação do dia</h3></div><button>+ Nova ordem</button></div><div className={styles.pickupBoard}>{[["Aguardando","3",["OC-1048 · Indústria Alfa","OC-1051 · Comercial Beta"]],["Em coleta","5",["OC-1042 · Fábrica Delta","OC-1045 · Centro Gama"]],["No terminal","8",["OC-1037 · Operação Sul","OC-1039 · Norte Distribuição"]]].map(([status,total,cards])=><section key={status as string}><header><b>{status as string}</b><span>{total as string}</span></header>{(cards as string[]).map((card,index)=><article key={card}><small>08:{index?"45":"20"}</small><b>{card}</b><span><IconPackage/> {index?"12 volumes":"8 volumes"}</span></article>)}</section>)}</div></div>}
      {active==="finance"&&<div className={styles.finance}><div className={styles.screenHead}><div><span>FLUXO DE CAIXA E FRETES</span><h3>Resultado da operação</h3></div><button>Últimos 6 meses</button></div><div className={styles.financeMetrics}><article><span>Receitas</span><b>R$ 284.620</b><small>+12,8%</small></article><article><span>Custos operacionais</span><b>R$ 186.410</b><small>-3,2%</small></article><article><span>Margem</span><b>34,5%</b><small>+4,1%</small></article></div><div className={styles.chart}><div>{[45,60,52,74,68,88].map((height,index)=><span key={index}><i style={{height:`${height}%`}}/><b>{["Fev","Mar","Abr","Mai","Jun","Jul"][index]}</b></span>)}</div><aside><small>TABELAS DE FRETE</small><b>18 tabelas ativas</b><p>Calcule valores por rota, peso, faixa e cliente.</p><button>Gerenciar tabelas</button></aside></div></div>}
    </div>
  </div>
}
