import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {IconArchive,IconArrowRight,IconBrandWhatsapp,IconBuilding,IconCash,IconCheck,IconFileCheck,IconFileInvoice,IconMapPin,IconPackage,IconRoute,IconSparkles,IconTable,IconTruck,IconUserCheck} from "@tabler/icons-react";
import {LogisticsExperience} from "./LogisticsExperience";
import {LogisticsForm} from "./LogisticsForm";
import styles from "./logistica.module.css";

const title="Loggxy Logística | Gestão completa para transportadoras";
const description="Gerencie frota, CT-e, documentos, rastreamento, romaneios, coletas, fluxo de caixa, tabelas de frete e clientes em uma só plataforma.";
export const metadata:Metadata={title,description,alternates:{canonical:"/logistica"},openGraph:{type:"website",locale:"pt_BR",url:"/logistica",siteName:"Loggxy Logística",title:"Sua operação logística sob controle",description:"Frota, CT-e, rastreamento, coletas, documentos e financeiro em um só sistema.",images:[{url:"/social/loggxy-logistica.png",width:1200,height:630,alt:"Loggxy Logística — gestão completa para transportadoras"}]},twitter:{card:"summary_large_image",title:"Loggxy Logística",description:"Controle a operação. Acompanhe cada carga.",images:["/social/loggxy-logistica.png"]}};

const categories=[
  {title:"Operação e cargas",description:"Do pedido de coleta à entrega final.",items:[[IconMapPin,"Rastreamento em tempo real","Acompanhe posição, rota, status e previsão de entrega da carga."],[IconPackage,"Romaneio de cargas","Organize volumes, documentos, veículos e destinos em cada viagem."],[IconRoute,"Controle de coletas","Programe, distribua e acompanhe coletas ao longo do dia."],[IconFileCheck,"Ordens de coleta","Registre solicitações, responsáveis, horários e situação operacional."]]},
  {title:"Fiscal e documentos",description:"Documentação vinculada à operação.",items:[[IconFileInvoice,"Gestor de CT-e","Emita, consulte e organize CT-es com informações centralizadas."],[IconArchive,"Cofre de arquivos","Armazene CT-es, XMLs, PDFs e documentos com busca organizada."],[IconFileCheck,"Comprovantes de entrega","Vincule comprovantes às cargas, clientes e documentos correspondentes."],[IconCheck,"CT-e simplificado","Separe e confira a documentação fiscal necessária para essa modalidade."]]},
  {title:"Gestão da transportadora",description:"Controle para decidir com mais clareza.",items:[[IconTruck,"Gerenciamento de veículos","Cadastre frota, disponibilidade, manutenção e situação dos veículos."],[IconCash,"Fluxo de caixa","Acompanhe receitas, custos, contas e resultado financeiro da operação."],[IconTable,"Tabelas de frete","Organize valores por rota, cliente, peso, faixa e tipo de serviço."],[IconUserCheck,"Cadastro de clientes","Centralize dados comerciais, fiscais, contatos e histórico de operações."]]},
];

export default function LogisticaPage(){return <main className={styles.page}>
  <header className={styles.header}><div><Link href="/logistica" className={styles.logo}><Image src="/brand/loggxy-logistica.png" width={50} height={50} alt="Loggxy Logística" priority/><span>Loggxy <b>Logística</b></span></Link><nav><a href="#recursos">Recursos</a><a href="#plataforma">Plataforma</a><a href="#contato">Contato</a></nav><a className={styles.headerCta} href="#contato">Solicitar demonstração <IconArrowRight/></a></div></header>
  <section className={styles.hero}><div className={styles.heroGlow}/><div className={styles.heroInner}><div className={styles.heroCopy}><div className={styles.eyebrow}><IconSparkles/> Gestão para transportadoras</div><h1>Controle a operação.<br/><em>Acompanhe cada carga.</em></h1><p>Frota, CT-e, documentos, coletas, rastreamento e financeiro conectados para sua transportadora operar com mais clareza.</p><div className={styles.heroActions}><a href="#contato">Quero conhecer <IconArrowRight/></a><a href="#plataforma">Explorar a plataforma</a></div><div className={styles.heroTrust}><span><IconCheck/> Transportadoras</span><span><IconCheck/> Operadores logísticos</span><span><IconCheck/> Frotas próprias</span></div></div><div className={styles.heroVisual}><div className={styles.logoHalo}><Image src="/brand/loggxy-logistica.png" width={420} height={420} alt="Logotipo Loggxy Logística" priority/></div><div className={`${styles.float} ${styles.floatTrack}`}><IconMapPin/><span><b>Rastreamento ao vivo</b>Carga em movimento</span></div><div className={`${styles.float} ${styles.floatCte}`}><IconFileInvoice/><span><b>CT-e organizado</b>Documentos conectados</span></div><div className={`${styles.float} ${styles.floatFleet}`}><IconTruck/><span><b>Frota sob controle</b>Veículos e viagens</span></div></div></div></section>
  <section className={styles.ribbon}><p><b>FROTA</b><i/> <b>CT-e</b><i/> <b>RASTREAMENTO</b><i/> <b>COLETAS</b><i/> <b>FINANCEIRO</b></p></section>
  <section id="recursos" className={styles.resources}><div className={styles.sectionHead}><span>OPERAÇÃO E GESTÃO NO MESMO SISTEMA</span><h2>Tudo separado por área. Tudo conectado na operação.</h2><p>Recursos estruturados para acompanhar o transporte do início ao fim.</p></div><div className={styles.categories}>{categories.map(category=><section key={category.title}><header><span>{category.title}</span><p>{category.description}</p></header><div>{category.items.map(([Icon,name,text])=><article key={name as string}><Icon/><div><h3>{name as string}</h3><p>{text as string}</p></div></article>)}</div></section>)}</div></section>
  <section id="plataforma" className={styles.platform}><div className={styles.sectionHead}><span>TORRE DE CONTROLE LOGGXY</span><h2>Veja sua operação em uma única visão.</h2><p>Explore os principais módulos da plataforma e acompanhe informações que mudam ao longo do dia.</p></div><LogisticsExperience/></section>
  <section className={styles.vault}><div className={styles.vaultInner}><div className={styles.vaultVisual}><div className={styles.safe}><IconArchive/><i/><span>COFRE DIGITAL</span></div>{[["CT-es e XMLs","Organizados"],["Comprovantes","Vinculados"],["Busca rápida","Por cliente ou carga"]].map(([title,text])=><article key={title}><IconCheck/><span><b>{title}</b>{text}</span></article>)}</div><div className={styles.vaultCopy}><span>DOCUMENTOS SEMPRE À MÃO</span><h2>Um cofre para os arquivos da sua operação.</h2><p>Centralize CT-es, comprovantes de entrega, XMLs, PDFs e documentos fiscais. Encontre cada arquivo pelo cliente, carga, viagem ou período.</p><ul><li><IconCheck/> Arquivos vinculados à operação</li><li><IconCheck/> Busca por documento ou cliente</li><li><IconCheck/> Organização de comprovantes</li><li><IconCheck/> Histórico acessível para conferência</li></ul><a href="#contato">Conhecer o cofre digital <IconArrowRight/></a></div></div></section>
  <section className={styles.simplified}><div className={styles.simplifiedInner}><IconFileInvoice/><div><span>PREPARAÇÃO DOCUMENTAL</span><h2>CT-e simplificado com a documentação organizada.</h2><p>Separe, confira e acompanhe os documentos fiscais necessários para essa modalidade, mantendo cada operação pronta para consulta e emissão.</p></div><a href="#contato">Quero saber mais <IconArrowRight/></a></div></section>
  <section id="contato" className={styles.contact}><div className={styles.contactCopy}><span>LOGGXY LOGÍSTICA</span><h2>Mais visibilidade para quem não pode perder o ritmo.</h2><p>Descubra como conectar cargas, documentos, frota, clientes e resultados em uma plataforma feita para a rotina logística.</p><div><IconBrandWhatsapp/><span><small>Fale agora com nossa equipe</small><a href="https://wa.me/5511965970699" target="_blank" rel="noreferrer">(11) 96597-0699</a></span></div></div><LogisticsForm/></section>
  <footer className={styles.footer}><div><Image src="/brand/loggxy-logistica.png" width={46} height={46} alt="Loggxy Logística"/><span><b>Loggxy Gerenciamento e Sistemas Ltda.</b><small>CNPJ: 63.700.987/0001-77</small></span></div><div><a href="mailto:contato@loggxy.com.br">contato@loggxy.com.br</a><a href="https://wa.me/5511965970699" target="_blank" rel="noreferrer">(11) 96597-0699</a></div><p>© {new Date().getFullYear()} Loggxy Logística. Todos os direitos reservados.</p></footer>
</main>}
